kafka_version: 3.1.0
scala_version: 2.13
kafka_dir: /opt/kafka
java_dir: "{{ java_path.stdout }}"
kafka_link: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"

###########################################################################################
#Extra kafka link: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{scala_version}}-{{ kafka_version }}.tgz"
###########################################################################################

# Server properties
delete_topic_enable: true
num_network_threads: 3
num_io_threads: 8
socket_send_buffer_bytes: 102400
socket_receive_buffer_bytes: 102400
socket_request_max_bytes: 104857600
log_dirs: /tmp/kafka-logs-1
num_partitions: 1
num_recovery_threads_per_data_dir: 1
default_replication_factor: 3
offsets_topic_replication_factor: 3
transaction_state_log_replication_factor: 3
transaction_state_log_min_isr: 2
min_insync_replicas: 2
acks_a: all
log_retention_hours: 168
log_segment_bytes: 1073741824
log_retention_check_interval_ms: 300000
zookeeper_connect: "{{ groups['kafka'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(':2181, ') + ':2181' }}"
zookeeper_connection_timeout_ms: 18000
group_initial_rebalance_delay_ms: 0